
test:
	sbt "run Testbench --backend c --compile --test --genHarness --targetDir ./build --vcd"

sysc:
	sbt "run Testbench --backend sysc --compile --test --genHarness --targetDir ./build --vcd"

clean:
	rm build/*
